name: Gradle Dependency Scan (Java 17)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"   # Mondays 02:00 UTC

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - uses: actions/checkout@v4

      # 2) Java 17 toolchain
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3) Cache Gradle (bump key if you change wrapper/plugins)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v5-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # 4) Prepare + cache OWASP Dependency-Check data (to avoid repeated NVD downloads)
      - name: Prepare Dependency-Check data dir
        run: echo "DC_DATA=$HOME/.dc-data" >> $GITHUB_ENV

      - name: Cache DC data
        uses: actions/cache@v4
        with:
          path: ${{ env.DC_DATA }}
          key: ${{ runner.os }}-dcdata-v2
          restore-keys: ${{ runner.os }}-dcdata-

      # One-time safety: clear corrupt/empty cache so the DB can re-warm cleanly
      - name: Reset DC data if empty/corrupt
        run: |
          if [ ! -s "$DC_DATA/cve.db" ]; then
            rm -rf "$DC_DATA"
            mkdir -p "$DC_DATA"
          fi

      # 5) (Debug) list gradle tasks so you can confirm the plugin tasks exist
      - name: Show available Gradle tasks
        run: ./gradlew tasks --all

      # 6) Outdated dependency report (requires ben-manes versions plugin in build.gradle)
      - name: Outdated dependencies
        run: ./gradlew dependencyUpdates --stacktrace --warning-mode=all

      # 7) OWASP CVE scan (inject NVD key both as env var and -D property)
      - name: OWASP CVE scan
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          DEPENDENCY_CHECK_NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          echo "NVD key len: ${#NVD_API_KEY} (first 4 chars masked: ${NVD_API_KEY:0:4}****)"
          ./gradlew dependencyCheckAnalyze \
            -Dorg.owasp.dependencycheck.nvd.api.key="${NVD_API_KEY}" \
            -Dorg.owasp.dependencycheck.data.directory="${DC_DATA}" \
            -Dorg.owasp.dependencycheck.failOnError=false \
            -Dorg.owasp.dependencycheck.failBuildOnCVSS=11 \
            --info --stacktrace --warning-mode=all

      # 8) Always upload reports so you can download them even if a step fails
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dep-reports
          path: |
            build/dependencyUpdates/**
            build/reports/**
