# .github/workflows/gradle-dep-scan.yml
name: Gradle Dependency Scan (Java 8)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"   # Mondays 02:00 UTC
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Outdated dependencies report (Gradle Versions Plugin)
        run: ./gradlew dependencyUpdates
      - name: OWASP Dependency-Check (HTML report)
        run: ./gradlew dependencyCheckAnalyze
      - name: Archive reports
        uses: actions/upload-artifact@v4
        with:
          name: dep-reports
          path: |
            build/dependencyUpdates/**
            build/reports/dependency-check-report.html
