name: Gradle Dependency Scan (Java 17)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"   # Mondays 02:00 UTC
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Outdated dependency report (Gradle Versions Plugin)
      - name: Outdated dependencies
        run: ./gradlew dependencyUpdates

      # OWASP Dependency-Check (HTML report)
      - name: OWASP CVE scan
        run: ./gradlew dependencyCheckAnalyze

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: dep-reports
          path: |
            build/dependencyUpdates/**
            build/reports/dependency-check-report.html
